# Generated by Django 3.0.2 on 2020-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryDisplayElement',
            fields=[
                ('entryOrder', models.IntegerField()),
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('readingsPrio', models.TextField()),
                ('readings', models.TextField()),
                ('writingsPrio', models.TextField()),
                ('writings', models.TextField()),
                ('pos', models.TextField()),
                ('xref', models.TextField()),
                ('ant', models.TextField()),
                ('misc', models.TextField()),
                ('lsource', models.TextField()),
                ('dial', models.TextField()),
                ('s_inf', models.TextField()),
                ('field', models.TextField()),
                ('lang', models.TextField()),
                ('gloss', models.TextField()),
            ],
            options={
                'db_table': 'unspecified',
                'managed': False,
            },
        ),
    ]
